<!DOCTYPE html>
<html>
<head>
  <title></title>
  <head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600' rel='stylesheet' type='text/css'>
<link href="//netdna.bootstrapcdn.com/font-awesome/3.1.1/css/font-awesome.css" rel="stylesheet">
<style type="text/css">
  body, div, dl, dt, dd, ul, ol, li, h1, h2, h3, h4, h5, h6, 
pre, form, fieldset, input, textarea, p, blockquote, th, td { 
  padding:4px;
  margin:0;

}
h1{
  margin-top: 20px;
  font-size: 20px;
}
fieldset, img {border:0}

ol, ul, li {list-style:none}

:focus {outline:none}

body,
input,
textarea,
select {
  font-family: 'Open Sans', sans-serif;
  font-size: 16px;
  color: #4c4c4c;
}
body{
  background-color: #ffffff;
}
#phone, #email, select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
}

h1 {
  font-size: 25px;
  font-style: bold;
  font-weight: 300;
  color: #4c4c4c;
  text-align: center;
  padding-top: 10px;
  margin-bottom: 10px;
}

html{
  background-color: #ffffff;
}

.testbox {
  margin: 20px auto;
  width: 343px; 
  height: 464px; 
  -webkit-border-radius: 8px/7px; 
  -moz-border-radius: 8px/7px; 
  border-radius: 8px/7px; 
  background-color: #ebebeb; 
  -webkit-box-shadow: 1px 2px 5px rgba(0,0,0,.31); 
  -moz-box-shadow: 1px 2px 5px rgba(0,0,0,.31); 
  box-shadow: 1px 2px 5px rgba(0,0,0,.31); 
  border: solid 1px #cbc9c9;
}

form{
  margin: 0 30px;
}


hr{
  color: #a9a9a9;
  opacity: 0.3;
}
#selector{
      margin-top: 50px;
}

.button {
    background-color: #3a57af;
    border: none;
    color: white;
    padding: 10px 14px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin-left: 90px;
    border-radius: 5px;
    cursor: pointer;
}


.button:hover {
  top: 3px;
  background-color:#2e458b;
  -webkit-box-shadow: none; 
  -moz-box-shadow: none; 

  box-shadow: none;
}

</style>

<body>
  <div class="testbox">
  
  <font face="Times New Roman"><h1>Please Enter Phone/E-Mail</h1></font>
<form action="<?php echo $block->getFormAction(); ?>" method="POST" >
 <select id="selector" name="selector" required>
    <option value="" >SELECT</option>
    <option value="phone" >PHONE</option>
    <option value="email" >E-MAIL</option>
</select><br/>
<div id="myinput">
  
</div>
 

<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
$FormKey = $objectManager->get('Magento\Framework\Data\Form\FormKey'); 
?>
<input name="form_key" type="hidden" value="<?php echo $FormKey->getFormKey();?>">


  <button class="button" type="Submit">Submit</button>
</form>
</div>
</body>
</html> $

<!-- <script>
    require([
'jquery'
], function ($) {
$(document).ready(function() {


  $("#selector").change(function() 
 {
     var option = $('#selector').val();
    if (option === 'phone') 
    {
      
      $('#myinput').html("<input type='text' id='phone' name='phone' required/>");
        // $('#phone').show();
        // $('#email').hide();
    }
    if (option === 'email') 
    {
        $('#myinput').html("<input type='email' id='email' name='email' required/>");
    }
  });

});
}); 



</script> -->